# Site settings
title: HilaryBerigan.com
header-img: img/home-bg.png
email: berigan.hilary@gmail.com
copyright_name: hilaryberigan
description: > # this means to ignore newlines until "baseurl:"
  The thoughts of an ADHD programmer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hilaryberigan
learn_profile: hilaryberigan
email_username: berigan.hilary@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
